# Lab 00 - A - Data Analysis In Python - First Steps

Machine learning and data analysis (that is usually also a pre-step for learning) deal with data. Thererefore we need tools to manipulate it and extract the information we want. In the Python environment there are two very useful packages for this: [`numpy`](https://numpy.org/doc/1.19/) and [`pandas`](https://pandas.pydata.org/docs/reference/index.html#api).

In this lab, we will take the first steps into using these packages and see some of their functionalities. These will be needed throughout the course. Both packages contain many useful functionalities, of which we will introduce only a few. To find out more about the other functionalities, the documentations, **Google** and **StackOverflow** are your best friends. 

In [11]:
# Load commonly used imports (such as numpy and pandas) and several utils functions that 
# are used thoughout different labs and code examples

import sys

sys.path.append("../")
from utils import *

ModuleNotFoundError: No module named 'plotly'

# Numpy - The Basics

Let us start with numpy. This package supports vector, matrix and tensor operations over numerical (but not just) data. It is very comfortable and much faster than `for` loops and classic `list` manipulations.

## Array Creation

There are multiple ways to create an array. We can create it from an existing list, load it from a file or generate a new array.


In [ ]:
array_1D = np.array([6, 2, 8, 4, 5, 10, 7, 143, 9, 10])
print(array_1D)
print(array_1D.shape)

In [12]:
array_2D = np.array(
	[[10, 20, 30, 40],
	 [100, 200, 300, 400],
	 [1000, 2000, 3000, 4000]])
print(array_2D)
print(array_2D.shape)

[[  10   20   30   40]
 [ 100  200  300  400]
 [1000 2000 3000 4000]]
(3, 4)


In [13]:
import numpy as np

array_3D = np.array(
	[[[10, 20, 30, 40], [100, 200, 300, 400], [1000, 2000, 3000, 4000]],
	 [[11, 21, 31, 41], [101, 201, 301, 401], [1001, 2001, 3001, 4001]]])
print(type(array_3D[0][0][0]))
print(array_3D)
print(array_3D.shape)

<class 'numpy.int32'>
[[[  10   20   30   40]
  [ 100  200  300  400]
  [1000 2000 3000 4000]]

 [[  11   21   31   41]
  [ 101  201  301  401]
  [1001 2001 3001 4001]]]
(2, 3, 4)


Using `numpy`'s functions for creating new arrays requires specifying the shape of the desired output array. This is an n-array tuple specifying the sizes of the different dimensions. 

*   Specifying the shape `(3)` will create a 1D array with 3 entries.
*   Specifying the shape `(10, 3)` will create a 2D matrix with 10 rows and 3 columns.
*   Specifying the shape `(10, 28, 28)` will create a 3D matrix (a tensor) which we can think of in the following manner: it is an object holding 10 2D matrices of size 28x28.





In [14]:
import numpy as np

# Initalize arrays with built-in numpy functions
zeros_3D = np.zeros((4, 5, 2))  # Create a 3D arrays of 0's
ones_2D = np.ones((4, 5))  # Create a 2D arrays of 1's
print(type(zeros_3D[0][0][0]))
print(zeros_3D)
print(ones_2D)

<class 'numpy.float64'>
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
np.arange(50)  # Create the vector [0, 1, 2, 3, 4, .. , 48, 49]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [16]:
# Create a vector of random integers from 5 to 50, with shape (2, 3)
np.random.randint(5, 50, (2, 3))

array([[ 5, 27, 47],
       [32, 10, 32]])

There are many other functions such as `np.full`, `np.eye`, `np.random.uniform`, etc. Next, let us load an existsing dataset into a numpy array. This specific dataset represents images.

In [17]:
img_array = np.loadtxt(open("../datasets/MNIST_Images.csv", "rb"),
					   delimiter=",").reshape(-1, 28, 28)
img_array.shape

(100, 28, 28)

In [18]:
import numpy as np

img_array = np.loadtxt(open("../datasets/MNIST_Images.csv", "rb"),
					   delimiter=",").reshape(-1, 28, 28)
img_array.shape
px.imshow(img_array[0]).show()

NameError: name 'px' is not defined

## Array indexing and slicing

A great strength of `numpy` is the ease in subsetting an array to retrieve only specific parts of it. We do so by indexing and slicing the arrays. For 1D arrays these operations are very similar to those over lists.  For arrays of higher dimensions, we use a comma to separate the slicing of each dimension. For example, accessing an element in the array `arr` in the first row and second column is done by: `arr[0, 1]` (recall indexing in python begins from zero). To select only the second column, over all rows write: `arr[:, 2]`

In [ ]:
import numpy as np

array_1D = np.array([10, 11, 12, 13, 14, 15, 16])
# Select 1st element
print("Select 1st element")
print(array_1D[1])

# Select all the elements from 1st to 4th element
print("\nSelect all the elements from 1st to 4th element")
print(array_1D[1:5])

# Select elements [1, 4]
print("\nSelect elements [1, 4]")
print(array_1D[[1, 4]])
print()

array_2D = np.array([[1, 2, 3, 4],
					 [5, 6, 7, 8],
					 [9, 10, 11, 12],
					 [13, 14, 15, 16],
					 [17, 18, 19, 20]])
# Select 1st row, 2nd column  
print(array_2D[1, 2])

randint_2D = np.random.randint(5, 50, (10, 20))
print("\nPrint random array")
print(randint_2D)

# Select from 3rd row to 5th, all the columns
print("\nSelect from 3rd row to 5th, all the columns")
print(randint_2D[2:5, :])

# Select from 3rd row to 5th, columns 1 and 2
print("\nSelect from 3rd row to 5th, columns 1 and 2")
print(randint_2D[2:5, 1:3])

# Select from 3d row to 5th, columns 3, 5, 6, and  11
print("\nSelect from 3rd row to 5th, columns 3, 5, 6, and  11")
print(randint_2D[2:5, [3, 5, 6, 11]])


## Matrix Operations
Another strength of the `numpy` package is that all matrix operations you can think of (and even more) are already implemented. For example, element-wise addition of scalar, multiplication, powering up a matrix, log-transformations and much more.

As `numpy` overloads the different mathematical operators, it is easy to write mathematical expressions over 2 (or more) vectors/matrices, such as summing or multiplying and also comparing their elements.


In [ ]:
import numpy as np

# Operations on 1 matrix
A = np.arange(1, 33).reshape(4,
							 8)  # Create an array of numbers from 1 ot 32, and then make a 2d array of 4 rows to 8 columns
print(A)

print("\n\nA + 1:")
print(A + 1)
print("\n2 * A:")
print(2 * A)
print("\nA*A*A:")
print(np.power(A, 3))
print("\nlog(A):")
print(np.log(A))
print("\nA Transpose:")
print(A.transpose())  # also np.transpose(A) and A.T are valid syntaxes
print("\n A > 10:")
print(A > 10)

# Operations on 2 matrices
A = np.arange(6).reshape([2, 3])
B = np.random.randint(1, 10, (2, 3))
print("A")
print(A)
print("\n\nB")
print(B)

print("\nA+B:")
print(A + B)  # Equivalent to np.add(a_array, b_array)
print("\n A * B (element-wise multiplication):")
print(np.multiply(A, B))
print("\n AB (matrix multiplication):")
print(A @ B.T)  # Equivalent to np.dot(a_array, b_array)

print("\nA > B")
print(A > B)


For many `numpy` operations we can specify the `axis` over which to perform the operation:

In [ ]:
# Concatenate matrices
print("\nConcatenate 2 arrays by the rows:")
print(np.concatenate((A, B), axis=0))  # Concatenate rows - look at the shape
print("\nConcatenate 2 arrays by the columns:")
print(
	np.concatenate((A, B), axis=1))  # Concatenate columns - look at the shape



##  Basic Statistics

You can easily calculate a lot of basic statistics from an array, such as the sum, mean, variance, maximum, argmax, etc. All of these can be retrieved either over the entire array or over rows/columns.

For each of these functions, you can get the statistic for: 
- the whole array: `np.stat(arr)`
- by row: `np.stat(arr, axis = 1)`
- by column: `np.stat(arr, axis = 0)`

In [ ]:
# Basic statistics of a matrix
A = np.arange(6).reshape([2, 3])
print("A")
print(A)

print("\n\nSum of the array")
print(np.sum(A))  # Sum all the matrix (return a scalar)
print("\nSum of the array by column")
print(np.sum(A, axis=0))  # Sum by column (return a vector)
print("\nSum of the array by row")
print(np.sum(A, axis=1))  # Sum by row (return a vector)

print("\nMax of each row")
print(np.max(A, axis=1))  # Max by column (return a vector)

print("\nMax of each column")
print(np.max(A, axis=0))  # Max by row (return a vector)

print("\nAverage of all the array")
print(np.mean(A))


## Sampling From Distributions

`numpy` provides a broad set of distributions to sample from. We will cover this in more depth in lab 2. 

In [ ]:
import numpy as np

A = np.random.randint(1, 15, size=20)
print("A")
print(A)

print("\n\nThe values that appear in the array")
print(np.unique(A))
print("\nHow many values are between [0, 5), [5, 10), [10, 15]")
print(np.histogram(A, bins=[0, 5, 10, 15]))

## Linear Algebra
One of the most important mathematical fields in machine learning is linear algebra. You can perform many of these operations using `numpy`. You can calculate the eigenvectors of a matrix, or its inverse, the rank of the matrix and so on.

In [ ]:
A = np.array([[1., 2.], [3., 4.]])
print("A")
print(A)
print("\n\nInverse of A")
print(np.linalg.inv(A))

B = np.diag((1, 2, 3))
print("\n\nB")
print(B)

eigvalues, eigvectors = np.linalg.eig(B)
print("\neigenvalues, eigenvectors")
print(eigvalues, eigvectors)

print("\nRank of the matrix")
print(np.linalg.matrix_rank(B))


## Reshaping

You can change the shape of your array, with transpose, flattening, reshape, 
adding a new axis (see `np.newaxis`)



In [ ]:
B = np.array([[1, 2, 3], [4, 5, 6]])

print("\n\nB")
print(B)

print("\nFlatten matrix")
print(np.ravel(B))

print("\nTranspose matrix")
print(B.transpose())

## Sorting

You can sort the matrix by row or by column

In [ ]:
B = np.array([[3, 6, 1, 4, 10], [5, 1, 8, 3, 65]])

print("B")
print(B)

print("\n\nSort by row")
print(np.sort(B, axis=1))


## Indexing By Condition


In [ ]:
A = np.random.randint(1, 30, (5, 4))
print("A")
print(A)

print("\nGet the numbers that are greater than 5:")
print(A[A > 5])

print("\nGet the numbers that are divisible by 4:")
print(np.extract(np.mod(A, 4) == 0, A))

## Let's practice!

To get you a bit more accustomed to `numpy` you are encouraged to solve the following challenges. If you choose to not solve the following challenges, be sure to understand the solutions. Do not use loops or list comprehensions.



Write a program to create a `7x10` matrix that has `0` and `1` staggered:
```
# 0 1 0 1 0 1 0
# 1 0 1 0 1 0 1
# 0 1 0 1 0 1 0
# 1 0 1 0 1 0 1
```
Hint: use slice operations on different axes.


In [ ]:
import numpy as np

A = np.zeros((7, 10))
A[::2, ::2] = 1
A[1::2, 1::2] = 1
print(A)

Calculate the volume of a cylinder with the following diameters and lengths:


In [ ]:
diameters = np.array([1, 3, 5, 2, 4])
lengths = np.array([10, 20, 3, 10, 5])

In [ ]:
print(np.array(np.power(diameters / 2, 2) * lengths * np.pi))

Write a function that receives 2 vectors and returns their cartesian product:
```
def create_cartesian_product(vec1, vec2):
  pass
```



In [ ]:
def cartesian_product(vec1, vec2):
	# np.repeat([1, 2, 3], 4) -> [1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]
	# np.tile([1, 2, 3], 4)   -> [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
	return np.array(
		(np.repeat(vec1, len(vec2)), np.tile(vec2, len(vec1)))).transpose()


print(cartesian_product([1, 2, 3], [4, 5, 6, 7]))

Given an array `a` and a number `n`, find the closest number to `n` in `a`:
```
def find_closest(a, n):
  pass
```



In [ ]:
def find_closest(a, n):
	a = np.array(a)
	return a[np.argmin(np.abs(a - n))]


print(find_closest([1, 24, 12, 13, 14], 10))

Check if the sudoku grid is valid:
*   Check that each row contains all the numbers from 1 to 9
*   Check that each column contains all the numbers from 1 to 9
*   Check that each of the 9 non-overlapping `3x3` blocks composing grid contain 1 to 9

You can assume it contains only integers and that the shape of the array is `9x9`
```
def check_sudoku(grid):
  pass
```



In [ ]:
import numpy as np


def cartesian_product(vec1, vec2):
	# np.repeat([1, 2, 3], 4) -> [1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]
	# np.tile([1, 2, 3], 4)   -> [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
	return np.array(
		(np.repeat(vec1, len(vec2)), np.tile(vec2, len(vec1)))).transpose()


def is_1_to_9(array):
	return np.all(np.sort(array) == np.arange(1, 10))


def check_sudoku(grid):
	def check_block(block):
		return is_1_to_9(np.ravel(grid[block[0] * 3:block[0] * 3 + 3],
								  grid[block[1] * 3:block[1] * 3 + 3]))

	if not is_1_to_9(np.unique(grid)):
		return False
	if not np.all(np.apply_along_axis(is_1_to_9, 0, grid)):
		return False
	if not np.all(np.apply_along_axis(is_1_to_9, 1, grid)):
		return False
	return np.all(np.apply_along_axis(check_block, 0,
									  cartesian_product([0, 1, 2], [0, 1, 2])))


assert check_sudoku(np.tile(np.arange(1, 10), 9).reshape((9, 9))) == False
assert check_sudoku(np.tile(np.arange(1, 10), 9).reshape((9, 9))) == True


# def is_1_to_9(array_):
#   # Return True if the array contains all the numbers from 1 to 9, False otherwise
#     return np.all(np.sort(array_, axis = None) == np.arange(1, 10))

# def check_sudoku(grid):
#     def check_block(coords_block):
#         return is_1_to_9(grid[coords_block[0]*3 : coords_block[0]*3+3, 
#                               coords_block[1]*3 : coords_block[1]*3+3])

#     grid = np.array(grid)

#     # Check that the grid contains only 1 to 9
#     if (not is_1_to_9(np.unique(grid))):
#         return False

#     # Check that each line/column contains 1 to 9:
#     # Sort each column. We expect it to be
#     # [[1, 1, 1, 1, 1, 1, 1, 1, 1], [2, 2, 2, 2, 2, 2, 2, 2] ... [9, 9, 9, 9, 9, 9, 9, 9, 9]]
#     # Thus we expect the sums of the rows: 1*9, 2*9....
#     if  np.any(np.sum(np.sort(grid, axis = 0), axis = 1) != np.arange(1, 10)*9):
#         return False

#     # Make the same for the columns
#     if np.any(np.sum(np.sort(grid.transpose(), axis = 0), axis = 1) != np.arange(1, 10)*9):
#         return False


#     # 0,0 0,0 0,0    0,1 0,1 0,1    0,2 0,2 0,2
#     # 0,0 0,0 0,0    0,1 0,1 0,1    0,2 0,2 0,2
#     # 0,0 0,0 0,0    0,1 0,1 0,1    0,2 0,2 0,2
#     #
#     #
#     # 1,0 1,0 1,0    1,1 1,1 1,1    1,2 1,2 1,2
#     # 1,0 1,0 1,0    1,1 1,1 1,1    1,2 1,2 1,2
#     # 1,0 1,0 1,0    1,1 1,1 1,1    1,2 1,2 1,2
#     #
#     #
#     # 2,0 2,0 2,0    2,1 2,1 2,1    2,2 2,2 2,2
#     # 2,0 2,0 2,0    2,1 2,1 2,1    2,2 2,2 2,2
#     # 2,0 2,0 2,0    2,1 2,1 2,1    2,2 2,2 2,2


#     # For each block of 9, check if it contains all the numbers 1 to 9
#     blocks_are_valid = np.apply_along_axis(check_block, 1, cartesian_product([0, 1, 2], [0, 1, 2]))
#     return np.all(blocks_are_valid)


Given a matrix, check if some row is a scalar multplication of another
```
def check_dependencies(matrix_):
  pass
```



In [ ]:
def check_dependencies(matrix_):
	matrix = np.array(matrix_)

	def rows_are_dependent(indices):
		if indices[0] == indices[1]:
			return False
		return np.unique(matrix[indices[0],] / matrix[indices[1],]).shape[
				   0] == 1

	return np.any(np.apply_along_axis(rows_are_dependent, 1, cartesian_product(
		np.arange(matrix.shape[0]), np.arange(matrix.shape[0]))))

# def check_dependencies(matrix_):
#     def rows_are_dependent(indices):
#         if indices[0] == indices[1]:
#             return False
#         return np.unique(matrix_[indices[0],] / matrix_[indices[1],]).shape[0] == 1
#
#     return np.any(np.apply_along_axis(rows_are_dependent, 1,
#                                       cartesian_product(np.arange(matrix_.shape[0]), np.arange(matrix_.shape[0]))))


Write a function that gets a 1D array and check if there is no local extrema point in addition to the global one.
```
def have_an_extrema(array):
  pass
```



In [ ]:
def have_a_maxima(array):
	argmax_arr = np.argmax(array[1:-1]) + 1
	before_max_neg = np.all(array[:argmax_arr - 1] - array[1:argmax_arr] < 0)
	after_max_neg = np.all(array[argmax_arr:-1] - array[argmax_arr + 1:] > 0)
	return before_max_neg and after_max_neg


def have_an_extrema(array):
	# Check if it is a monotonic series
	if np.unique(array[:-1] - array[1:]).shape[0] == 1: return True

	# If there is a minimum, we can look for a maximum in the negated array
	return have_a_maxima(array) or have_a_maxima(-array)


have_an_extrema(np.array([1, 2, 4, 5]))

Note that instead of `array[:argmax_arr - 1] - array[1:argmax_arr]`, you could use the `np.diff` function


# Pandas
Until now, we have only looked at numerical data. But in real-world problems, we also have textual and categorical data. To manipulate this type of data, we will use the `pandas` library. One of the basic data structures of `pandas` is called a `DataFrame`. Generally, in a `DataFrame`, each row is a different sample and each column is a feature.

For example, each row can represent a student, with columns of the ID, birthday, and gender of the student. 

`pandas` has a lot of possibilities of which we are going to introduce a very small subset.

## Array Creation

In addition to creating an array from lists or randomly generated data frames, we are going to use an existing dataset of house prices (you will get back to this dataset in excercise 2).

In [ ]:
import pandas as pd

# Load https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data?select=train.csv
df = pd.read_csv('../datasets/house_train.csv', index_col=0)
df.head()

In [ ]:
import pandas as pd

df = pd.read_csv('../datasets/house_train.csv', index_col=0)
print("\nRows Names")
print(df.index)
print("\nColumns Names")
print(df.columns)
print("\nDf train shape")
print(df.shape)

## Indexing And Slicing
Just like when using `numpy` you can select a subset of rows and columns. You can do it using indices or using names of the rows and columns. You can easily add a new column based on existing ones.

In [ ]:
print("\ndf[['GrLivArea', 'SalePrice', 'BedroomAbvGr']]")
print(df[['GrLivArea', 'SalePrice',
		  'BedroomAbvGr']])  # Select  GrLivArea columns SalePrice BedroomAbvGr

print("\ndf.loc[3:10,['GrLivArea', 'SalePrice', 'BedroomAbvGr'] ]")
print(df.loc[3:10, ['GrLivArea', 'SalePrice', 'BedroomAbvGr']])

print("\ndf.iloc[[3, 4, 5]]")
print(df.iloc[[3, 4, 5]])
print("\ndf.iloc[3:10,[6, 7, 8]]")
print(df.iloc[3:10, [6, 7, 8]])

In [19]:
import pandas as pd
import numpy as np

individual_df = pd.DataFrame(np.array([np.random.randint(2000000, 3000000, 50),
									   np.random.uniform(1.50, 1.70, size=50),
									   np.random.uniform(45, 90,
														 size=50)]).transpose(),
							 columns=['ID', 'Height', 'Weight'])

individual_df["BMI"] = individual_df["Weight"] / individual_df["Height"].pow(2)
print("\nIndividual DF")
print(individual_df.head())


Individual DF
          ID    Height     Weight        BMI
0  2842094.0  1.531202  79.570048  33.937871
1  2161531.0  1.504826  56.477663  24.940434
2  2923105.0  1.638746  60.400530  22.491462
3  2759674.0  1.694881  51.457710  17.913154
4  2150595.0  1.540998  89.748243  37.793890


# Basic Statistics
`pandas` provides different statistical functions over `DataFrame`s.

In [21]:
import pandas as pd

df = pd.read_csv('../datasets/house_train.csv', index_col=0)
print("\nMedian of the SalePrice column")
print(df.SalePrice.median())

print("\nSelecting rows by condition")
median_price = df.SalePrice.median()
print(df[df.SalePrice > median_price].head())



Median of the SalePrice column
163000.0

Selecting rows by condition
    MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
Id                                                                    
1           60       RL         65.0     8450   Pave   NaN      Reg   
2           20       RL         80.0     9600   Pave   NaN      Reg   
3           60       RL         68.0    11250   Pave   NaN      IR1   
5           60       RL         84.0    14260   Pave   NaN      IR1   
7           20       RL         75.0    10084   Pave   NaN      Reg   

   LandContour Utilities LotConfig  ... PoolArea PoolQC Fence MiscFeature  \
Id                                  ...                                     
1          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
2          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   
3          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
5          Lvl    AllPub       FR2  ...        

## Group-by

When working with data that contains also a categorical feature, we are often interested in performing some kind of calculation over all rows containing the same categorical value. For example, given a data frame of student grades for different courses, we can calculate the students' average grade.

In [36]:
import pandas as pd
import numpy as np

students_df = pd.DataFrame(np.array(
	[np.random.choice(["Zohar", "Shelly", "Omer", "Avi"], 50),
	 np.random.choice(["Linearit", "Intro", "Infi", "Probabilistic"], 50),
	 np.random.randint(80, 101, 50)]).transpose(),
						   columns=['Name', 'Course', 'Grade'])
students_df["Grade"] = students_df["Grade"].astype(int)

print("\n\nStudents df")
print(students_df.head())

print("\n\nCalculate average by student and by course")
print(students_df.groupby(['Name', 'Course']).mean().reset_index())



Students df
     Name         Course  Grade
0   Zohar  Probabilistic     92
1  Shelly       Linearit     98
2  Shelly          Intro     90
3     Avi           Infi     94
4  Shelly       Linearit    100


Calculate average by student and by course
      Name         Course      Grade
0      Avi           Infi  91.400000
1      Avi          Intro  89.000000
2      Avi       Linearit  86.833333
3      Avi  Probabilistic  95.000000
4     Omer           Infi  89.750000
5     Omer          Intro  83.000000
6     Omer       Linearit  92.000000
7     Omer  Probabilistic  89.500000
8   Shelly           Infi  84.500000
9   Shelly          Intro  89.500000
10  Shelly       Linearit  98.200000
11  Shelly  Probabilistic  91.000000
12   Zohar           Infi  87.333333
13   Zohar          Intro  88.250000
14   Zohar       Linearit  96.000000
15   Zohar  Probabilistic  91.166667


## Sorting
As in `numpy` you can sort data frame based on a column

In [38]:
students_df.sort_values(ascending=False, by='Grade').head()

Name         Course  Grade
4   Shelly       Linearit    100
39  Shelly       Linearit    100
38   Zohar  Probabilistic     99
40  Shelly       Linearit     99
9      Avi  Probabilistic     99

## Executing Functions By Columns

In `pandas`, you can select columns and apply functions to them. You also can apply functions by elements.

In [41]:
df = pd.DataFrame(np.random.randint(1, 10, (5, 3)),
				  columns=['col1', 'col2', 'col3'])

print("\n\ndf")
print(df)
print("\nCalculate the difference between the min and the max of each column")
print(df.apply(lambda x: x.max() - x.min()))

# Apply by element
print("\nMultiply elements by 100")
print(df.applymap(lambda x: x * 100))

print("\n\nIterate over the columns")
print("\n-----------------------")
for key, value in df.iteritems():
	print(key, value)

print("\n\nIterate over the rows")
print("\n-----------------------")
for row_idx, row in df.iterrows():
	print(row_idx, row)



df
   col1  col2  col3
0     7     4     8
1     9     6     7
2     8     5     2
3     7     1     1
4     4     4     2

Calculate the difference between the min and the max of each column
col1    5
col2    5
col3    7
dtype: int32

Multiply elements by 100
   col1  col2  col3
0   700   400   800
1   900   600   700
2   800   500   200
3   700   100   100
4   400   400   200


Iterate over the columns

-----------------------
col1 0    7
1    9
2    8
3    7
4    4
Name: col1, dtype: int32
col2 0    4
1    6
2    5
3    1
4    4
Name: col2, dtype: int32
col3 0    8
1    7
2    2
3    1
4    2
Name: col3, dtype: int32


Iterate over the rows

-----------------------
0 col1    7
col2    4
col3    8
Name: 0, dtype: int32
1 col1    9
col2    6
col3    7
Name: 1, dtype: int32
2 col1    8
col2    5
col3    2
Name: 2, dtype: int32
3 col1    7
col2    1
col3    1
Name: 3, dtype: int32
4 col1    4
col2    4
col3    2
Name: 4, dtype: int32


## Merging Data Frames


In [44]:
# Concatenate data frames
import pandas as pd

# Create 2 data frames
ids_df1 = pd.DataFrame({
	'ID': ['336097897', '32109678', '25976389', '32438509', '36790307'],
	'name': ['Amos', 'Eran', 'Sapir', 'Amichai', 'Hadar'],
	'gender': ["M", "M", "F", "M", "F"]})

ids_df2 = pd.DataFrame({
	'ID': ['21370565', '34256798', '3908412', '326780578'],
	'name': ['Matan', 'Gabriel', 'Anael', 'Liora'],
	'gender': ["M", "M", "F", "F"]})

print("\n\ndf1")
print(ids_df1)
print("\ndf2")
print(ids_df2)
print("\n\nJoin the two dataframes along rows:")
concatenate_data = pd.concat([ids_df1, ids_df2])
print(concatenate_data)



df1
          ID     name gender
0  336097897     Amos      M
1   32109678     Eran      M
2   25976389    Sapir      F
3   32438509  Amichai      M
4   36790307    Hadar      F

df2
          ID     name gender
0   21370565    Matan      M
1   34256798  Gabriel      M
2    3908412    Anael      F
3  326780578    Liora      F


Join the two dataframes along rows:
          ID     name gender
0  336097897     Amos      M
1   32109678     Eran      M
2   25976389    Sapir      F
3   32438509  Amichai      M
4   36790307    Hadar      F
0   21370565    Matan      M
1   34256798  Gabriel      M
2    3908412    Anael      F
3  326780578    Liora      F


In [45]:
birthdates_id = pd.DataFrame({
	'ID': ['336097897', '32109678', '25976389', '32438509', '36790307',
		   '21370565', '34256798', '3908412', '326780578'],
	'birth_year': [1995, 1996, 1993, 1994, 1997, 1991, 1994, 1992, 1996]})

print("\nNow join the result_data and df_exam_data along ID:")
pd.merge(concatenate_data, birthdates_id, on='ID')


Now join the result_data and df_exam_data along ID:


ID     name gender  birth_year
0  336097897     Amos      M        1995
1   32109678     Eran      M        1996
2   25976389    Sapir      F        1993
3   32438509  Amichai      M        1994
4   36790307    Hadar      F        1997
5   21370565    Matan      M        1991
6   34256798  Gabriel      M        1994
7    3908412    Anael      F        1992
8  326780578    Liora      F        1996

## Let's Practice!

Let us create a table of flight companies' flights. Each row will represent a single flight and will have 3 features: city of departure, city of destination and price. 

Implement a function `create_flight_df` that recieves a collection of cities and creates a dataset of randomly selected flights and a price in the range of 100-400.

```
    def create_flight_df(cities_poss, nrows = 100):
        pass
```

The output data frame must not have more than a single record for any pair of cities. There are no flights from a city to itself.

In [46]:
import numpy as np
import pandas as pd


def create_flight_df(cities, nrows=20):
	df = pd.DataFrame([], columns=["Departure", "Destination", "Price"])

	while df.shape[0] < nrows:
		dep, dest = np.random.choice(cities, size=2, replace=False)
		price = np.random.randint(100, 400)

		if not ((df["Departure"] == dep) & (df["Destination"] == dest)).any():
			df = df.append(
				{"Departure": dep, "Destination": dest, "Price": price},
				ignore_index=True)
	return df


cities = ["Beijing", "Moscow", "New-York", "Tokyo", "Paris", "Cairo",
		  "Santiago", "Lima", "Kinshasa", "Singapore",
		  "New-Delhi", "London", "Ankara", "Nairobi", "Ottawa", "Seoul",
		  "Tehran", "Guatemala", "Caracas", "Vienna"]

flights = create_flight_df(cities)
flights.head()

Departure Destination Price
0   Nairobi    Kinshasa   170
1  New-York        Lima   343
2  Santiago   Singapore   122
3      Lima      London   113
4      Lima       Seoul   297

As there are pairs of cities with no direct flight between them, let us find the pairs of cities that have a single connection flight between them and calculate the total price of the flgihts. To do so merge the two data frames. This operation is often referred to as "joining" with the options of inner, outer, left, right and cross joining. For more about merging `pandas` data frames read the [documentation](https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html#database-style-dataframe-or-named-series-joining-merging).

In [47]:
df = pd.merge(flights, flights, left_on=["Destination"],
			  right_on=["Departure"], how="inner")
df = df[df.Departure_x != df.Destination_y]
df["Total_Price"] = df["Price_x"] + df["Price_y"]

df.head()

Departure_x Destination_x Price_x Departure_y Destination_y Price_y  \
0    New-York          Lima     343        Lima        London     113   
1    New-York          Lima     343        Lima         Seoul     297   
2    Santiago     Singapore     122   Singapore        Ankara     180   
3        Lima         Seoul     297       Seoul        Tehran     193   
4     Nairobi         Seoul     355       Seoul        Tehran     193   

  Total_Price  
0         456  
1         640  
2         302  
3         490  
4         548

Create a data frame with all flights of no connection and single connection.

In [48]:
flights = flights.append(df[["Departure_x", "Destination_y", "Total_Price"]]
						 .rename(
	columns={"Departure_x": "Departure", "Destination_y": "Destination",
			 "Total_Price": "Price"}))
flights

Departure Destination Price
0     Nairobi    Kinshasa   170
1    New-York        Lima   343
2    Santiago   Singapore   122
3        Lima      London   113
4        Lima       Seoul   297
5      Ankara   New-Delhi   214
6      Ottawa      London   257
7      Tehran      Vienna   110
8       Seoul      Tehran   193
9       Tokyo      London   190
10     Moscow    Kinshasa   146
11      Paris     Caracas   378
12  Singapore      Ankara   180
13    Nairobi       Seoul   355
14      Cairo   Guatemala   350
15    Nairobi      Ankara   141
16    Beijing      London   337
17     Ottawa     Caracas   391
18  Guatemala       Cairo   335
19   New-York      London   295
0    New-York      London   456
1    New-York       Seoul   640
2    Santiago      Ankara   302
3        Lima      Tehran   490
4     Nairobi      Tehran   548
5       Seoul      Vienna   303
6   Singapore   New-Delhi   394
7     Nairobi   New-Delhi   355

Since now we might have more than one way to flight between each pair of cities, let us find the cheapest flight option, with one connection, between two cities.

In [53]:
min_by_group = df.groupby(["Departure_x", "Destination_y"], as_index=False)[
	"Total_Price"].min()
min_by_group

Departure_x Destination_y  Total_Price
0        Lima        Tehran          490
1     Nairobi     New-Delhi          355
2     Nairobi        Tehran          548
3    New-York        London          456
4    New-York         Seoul          640
5    Santiago        Ankara          302
6       Seoul        Vienna          303
7   Singapore     New-Delhi          394

And if we want to know on average what is the most expensive city to fly to then:

In [54]:
mean_by_dest = min_by_group.groupby("Destination_y")["Total_Price"].mean()
expensive_city = mean_by_dest.idxmax()
expensive_city

'Seoul'